# Sweetie Bot base movement request.
# 
# * gait_type --- one of posible gaits. Only free gait supports end effector end pose without contact.
# * duration --- motion duration
# * steps --- the number of step cycles, it is ignored in STEPS mode.
# * base_goal --- goal pose of robot base
# * ee_goal --- goal poses for end effector. For free gait their order defines step sequece.
# * position_tolerance --- admissable position error.
# * orientation_tolerance  --- admissable orientaton error.
#
int32 gait_type
float64 duration
uint32 steps

geometry_msgs/Pose base_goal
sweetie_bot_kinematics_msgs/EndEffectorGoal[] ee_goal

float64 position_tolerance
float64 orientation_tolerance

int32 STEPS = 0 
int32 GAIT_STEP = 1
int32 GAIT_TROT = 2
---
int32 error_code
string error_string

int32 SUCCESSFUL = 0
int32 NO_SOLUTION = -1 #
int32 INVALID_END_EFFECTOR = -2
int32 UNABLE_TO_APPEND = -3
int32 TOLERANCE_VIOLATED = -4
---
duration time_from_start
